// This file is generated by Slice Machine. Update with care!

import Bounty from './Bounty';
import FaqQuestion from './FaqQuestion';

export {
	Bounty,
	FaqQuestion,
};

export const components = {
	bounty: Bounty,
	faq_question: FaqQuestion,
};
